// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parish_bookstore.Models;

#nullable disable

namespace parish_bookstore.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    [Migration("20220603141008_CartMigration")]
    partial class CartMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("parish_bookstore.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookCategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1,
                            CategoryName = "unassigned"
                        },
                        new
                        {
                            BookCategoryId = 2,
                            CategoryName = "Prayer & Service Books"
                        },
                        new
                        {
                            BookCategoryId = 3,
                            CategoryName = "Fathers & Patristics"
                        },
                        new
                        {
                            BookCategoryId = 4,
                            CategoryName = "Spiritual Development"
                        },
                        new
                        {
                            BookCategoryId = 5,
                            CategoryName = "Church History"
                        },
                        new
                        {
                            BookCategoryId = 6,
                            CategoryName = "Liturgics & Services"
                        });
                });

            modelBuilder.Entity("parish_bookstore.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("parish_bookstore.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("parish_bookstore.Models.GeneralItemCategory", b =>
                {
                    b.Property<int>("GeneralItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneralItemCategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeneralItemCategoryId");

                    b.ToTable("GeneralItemCategories");

                    b.HasData(
                        new
                        {
                            GeneralItemCategoryId = 1,
                            CategoryName = "unassigned"
                        },
                        new
                        {
                            GeneralItemCategoryId = 2,
                            CategoryName = "Gifts"
                        },
                        new
                        {
                            GeneralItemCategoryId = 3,
                            CategoryName = "Cross Necklaces"
                        },
                        new
                        {
                            GeneralItemCategoryId = 4,
                            CategoryName = "Seasonal"
                        });
                });

            modelBuilder.Entity("parish_bookstore.Models.HomeAltarItemCategory", b =>
                {
                    b.Property<int>("HomeAltarItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeAltarItemCategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HomeAltarItemCategoryId");

                    b.ToTable("AltarItemCategories");

                    b.HasData(
                        new
                        {
                            HomeAltarItemCategoryId = 1,
                            CategoryName = "unassigned"
                        },
                        new
                        {
                            HomeAltarItemCategoryId = 2,
                            CategoryName = "Censers"
                        },
                        new
                        {
                            HomeAltarItemCategoryId = 3,
                            CategoryName = "Charcoal"
                        },
                        new
                        {
                            HomeAltarItemCategoryId = 4,
                            CategoryName = "Incense"
                        },
                        new
                        {
                            HomeAltarItemCategoryId = 5,
                            CategoryName = "Vigil Lamps & Supplies"
                        });
                });

            modelBuilder.Entity("parish_bookstore.Models.IconCategory", b =>
                {
                    b.Property<int>("IconCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IconCategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IconCategoryId");

                    b.ToTable("IconCategories");

                    b.HasData(
                        new
                        {
                            IconCategoryId = 1,
                            CategoryName = "unassigned"
                        },
                        new
                        {
                            IconCategoryId = 2,
                            CategoryName = "Christ"
                        },
                        new
                        {
                            IconCategoryId = 3,
                            CategoryName = "Theotokos"
                        },
                        new
                        {
                            IconCategoryId = 4,
                            CategoryName = "Angels"
                        },
                        new
                        {
                            IconCategoryId = 5,
                            CategoryName = "Saints"
                        },
                        new
                        {
                            IconCategoryId = 6,
                            CategoryName = "Feasts"
                        });
                });

            modelBuilder.Entity("parish_bookstore.Models.TempModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Temp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = ""
                        });
                });

            modelBuilder.Entity("parish_bookstore.Models.TestUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
